.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SM-CHECK 1  "check " 
.SH NAME
check \- Check workspace health
.SH SYNOPSIS
\fBcheck\fR [\fB\-\-fix\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check workspace health
.SH OPTIONS
.TP
\fB\-\-fix\fR
Remove stale workspace entries from global config
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
