.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SM-CREDENTIAL 1  "credential " 
.SH NAME
credential \- Manage credentials (encrypted store)
.SH SYNOPSIS
\fBcredential\fR [\fB\-\-add\fR] [\fB\-\-label\fR] [\fB\-\-cred\-type\fR] [\fB\-\-list\fR] [\fB\-\-show\fR] [\fB\-\-status\fR] [\fB\-\-rm\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATH_OR_ID\fR> 
.SH DESCRIPTION
Manage credentials (encrypted store)
.SH OPTIONS
.TP
\fB\-\-add\fR
Add a credential (requires \-\-label and \-\-type)
.TP
\fB\-\-label\fR \fI<LABEL>\fR
Credential label
.TP
\fB\-\-cred\-type\fR \fI<CRED_TYPE>\fR
Credential type (url, username_password, api_key, bearer_token, vpn_config, ssh_key, custom)
.TP
\fB\-\-list\fR
List credentials for an engagement
.TP
\fB\-\-show\fR
Show full credential (including value)
.TP
\fB\-\-status\fR \fI<STATUS>\fR
Update credential status (not_verified, working, not_working, expired)
.TP
\fB\-\-rm\fR
Remove credential
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATH_OR_ID\fR>
Engagement path or credential ID
