.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SM-EVIDENCE 1  "evidence " 
.SH NAME
evidence \- Manage evidence files
.SH SYNOPSIS
\fBevidence\fR [\fB\-\-add\fR] [\fB\-\-list\fR] [\fB\-\-show\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATH\fR> 
.SH DESCRIPTION
Manage evidence files
.SH OPTIONS
.TP
\fB\-\-add\fR \fI<ADD>\fR
Add a file to evidence
.TP
\fB\-\-list\fR
List evidence files
.TP
\fB\-\-show\fR \fI<SHOW>\fR
Show/open an evidence file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATH\fR>
Engagement path
