.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SM-NOTE 1  "note " 
.SH NAME
note \- Create a quick note or export notes
.SH SYNOPSIS
\fBnote\fR [\fB\-\-export\fR] [\fB\-\-to\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATH\fR> [\fIMESSAGE\fR] 
.SH DESCRIPTION
Create a quick note or export notes
.SH OPTIONS
.TP
\fB\-\-export\fR \fI<EXPORT>\fR
Export format (markdown, html, pdf, json)
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
markdown
.IP \(bu 2
html
.IP \(bu 2
pdf
.IP \(bu 2
json
.RE
.TP
\fB\-\-to\fR \fI<TO>\fR
Output path for export
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATH\fR>
Engagement path
.TP
[\fIMESSAGE\fR]
Note message (omit when using \-\-export)
