.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SM-RM 1  "rm " 
.SH NAME
rm \- Remove an entity (prompts for confirmation unless \-\-yes)
.SH SYNOPSIS
\fBrm\fR [\fB\-\-yes\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATH\fR> 
.SH DESCRIPTION
Remove an entity (prompts for confirmation unless \-\-yes)
.SH OPTIONS
.TP
\fB\-\-yes\fR
Skip confirmation prompt
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATH\fR>
Path to entity
