.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH SM-SEARCH 1  "search " 
.SH NAME
search \- Search workspace Markdown files
.SH SYNOPSIS
\fBsearch\fR [\fB\-\-type\fR] [\fB\-\-client\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIQUERY\fR> 
.SH DESCRIPTION
Search workspace Markdown files
.SH OPTIONS
.TP
\fB\-\-type\fR \fI<TYPE>\fR
Filter by entity type (finding, requirement, note, scope, template, document)
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
finding
.IP \(bu 2
requirement
.IP \(bu 2
note
.IP \(bu 2
scope
.IP \(bu 2
template
.IP \(bu 2
document
.RE
.TP
\fB\-\-client\fR \fI<CLIENT>\fR
Limit to a specific client
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIQUERY\fR>
Search query
