import * as fs from 'fs';

function writeJson(path, arr) {
  fs.writeFileSync(path, JSON.stringify(arr, null, 2));
}

const web = [
  { name: "A01:2025-Broken Access Control", subcategory: "owasp-web-2025", content: JSON.stringify({ title: "Broken Access Control", severity: "high", overview: "Access control weaknesses allow users to act outside their intended permissions.", summary: "Broken access control occurs when restrictions are not properly enforced.", affected_endpoints: [{ method: "GET", path: "/api/users/{id}", description: "IDOR" }], evidence: [{ title: "IDOR", request: "GET /api/users/1234", response: "200 OK with victim data" }], impact_items: [{ title: "Unauthorized Data Access", explanation: "Attackers can access other users' data." }], remediation_items: [{ action: "Server-side access control", fix: "Never rely on client-side controls.", code_snippet: null }], steps_to_reproduce: "1. Log in. 2. Access another user's ID. 3. Observe data returned.", references: [{ title: "OWASP A01", url: "https://owasp.org/Top10/A01_2025/" }] }) },
  { name: "A02:2025-Cryptographic Failures", subcategory: "owasp-web-2025", content: JSON.stringify({ title: "Cryptographic Failures", severity: "high", overview: "Sensitive data is inadequately protected.", summary: "Weak algorithms, hardcoded keys, missing TLS.", affected_endpoints: [{ method: "GET", path: "/", description: "Missing HSTS" }], evidence: [{ title: "Weak cipher", request: "nmap --script ssl-enum-ciphers", response: "TLS_RSA_WITH_3DES_EDE_CBC_SHA supported" }], impact_items: [{ title: "Data Breach", explanation: "Sensitive data can be intercepted." }], remediation_items: [{ action: "Enforce TLS 1.3", fix: "Disable weak protocols.", code_snippet: null }], steps_to_reproduce: "1. Scan TLS. 2. Identify weak ciphers.", references: [{ title: "OWASP A02", url: "https://owasp.org/Top10/A02_2025/" }] }) },
  { name: "A03:2025-Injection", subcategory: "owasp-web-2025", content: JSON.stringify({ title: "Injection", severity: "critical", overview: "Untrusted data sent to an interpreter.", summary: "SQL, NoSQL, OS command, LDAP injection.", affected_endpoints: [{ method: "POST", path: "/api/search", description: "User input concatenated into SQL" }], evidence: [{ title: "SQLi", request: "POST /api/search?q=' OR '1'='1", response: "200 OK with all records" }], impact_items: [{ title: "Data Theft", explanation: "Arbitrary database records can be read." }], remediation_items: [{ action: "Parameterized queries", fix: "Use prepared statements.", code_snippet: null }], steps_to_reproduce: "1. Identify input fields. 2. Test SQL payloads.", references: [{ title: "OWASP A03", url: "https://owasp.org/Top10/A03_2025/" }] }) },
  { name: "A04:2025-Insecure Design", subcategory: "owasp-web-2025", content: JSON.stringify({ title: "Insecure Design", severity: "medium", overview: "Fundamental architecture flaws.", summary: "Missing or ineffective control design.", affected_endpoints: [{ method: "POST", path: "/transfer", description: "No anti-CSRF token" }], evidence: [{ title: "Missing transaction integrity", request: "POST /transfer", response: "200 OK" }], impact_items: [{ title: "Business Logic Abuse", explanation: "Missing compensating controls." }], remediation_items: [{ action: "Threat modeling", fix: "Model threats during design.", code_snippet: null }], steps_to_reproduce: "1. Review architecture. 2. Identify flows without controls.", references: [{ title: "OWASP A04", url: "https://owasp.org/Top10/A04_2025/" }] }) },
  { name: "A05:2025-Security Misconfiguration", subcategory: "owasp-web-2025", content: JSON.stringify({ title: "Security Misconfiguration", severity: "medium", overview: "Insecure defaults and verbose errors.", summary: "Most commonly seen vulnerability.", affected_endpoints: [{ method: "OPTIONS", path: "/", description: "Verbose server info" }], evidence: [{ title: "Stack trace", request: "GET /api/users/search?sort=invalid", response: "500 with stack trace" }], impact_items: [{ title: "Information Disclosure", explanation: "Config leaks reveal architecture." }], remediation_items: [{ action: "Harden config", fix: "Disable unnecessary features.", code_snippet: null }], steps_to_reproduce: "1. Send malformed requests. 2. Observe verbose errors.", references: [{ title: "OWASP A05", url: "https://owasp.org/Top10/A05_2025/" }] }) },
  { name: "A06:2025-Vulnerable Components", subcategory: "owasp-web-2025", content: JSON.stringify({ title: "Vulnerable and Outdated Components", severity: "high", overview: "Components with known vulnerabilities.", summary: "Libraries, frameworks with published CVEs.", affected_endpoints: [{ method: "GET", path: "/", description: "Server header reveals version" }], evidence: [{ title: "Known vulnerable version", request: "curl -I /", response: "Server: Apache/2.4.41" }], impact_items: [{ title: "RCE", explanation: "Published CVEs exist." }], remediation_items: [{ action: "SCA tools", fix: "Identify and update vulnerable deps.", code_snippet: null }], steps_to_reproduce: "1. Identify versions. 2. Correlate with CVEs.", references: [{ title: "OWASP A06", url: "https://owasp.org/Top10/A06_2025/" }] }) },
  { name: "A07:2025-Auth Failures", subcategory: "owasp-web-2025", content: JSON.stringify({ title: "Identification and Authentication Failures", severity: "critical", overview: "Weak authentication mechanisms.", summary: "Weak passwords, session fixation, missing MFA.", affected_endpoints: [{ method: "POST", path: "/api/auth/login", description: "No brute force protection" }], evidence: [{ title: "Unlimited login attempts", request: "POST /login", response: "403 with no rate limit" }], impact_items: [{ title: "Account Takeover", explanation: "Brute force and session hijacking." }], remediation_items: [{ action: "MFA", fix: "Enforce WebAuthn/FIDO2.", code_snippet: null }], steps_to_reproduce: "1. Attempt 100 logins. 2. Observe no rate limit.", references: [{ title: "OWASP A07", url: "https://owasp.org/Top10/A07_2025/" }] }) },
  { name: "A08:2025-Integrity Failures", subcategory: "owasp-web-2025", content: JSON.stringify({ title: "Software and Data Integrity Failures", severity: "high", overview: "Missing integrity protections.", summary: "Deserialization of untrusted data, untrusted updates.", affected_endpoints: [{ method: "POST", path: "/api/upload", description: "Deserializes untrusted data" }], evidence: [{ title: "Insecure deserialization", request: "POST /upload", response: "200 OK after deserialization" }], impact_items: [{ title: "RCE", explanation: "Deserialization leads to RCE." }], remediation_items: [{ action: "Avoid native deserialization", fix: "Use JSON or signed objects.", code_snippet: null }], steps_to_reproduce: "1. Identify deserialization endpoints. 2. Craft payloads.", references: [{ title: "OWASP A08", url: "https://owasp.org/Top10/A08_2025/" }] }) },
  { name: "A09:2025-Logging Failures", subcategory: "owasp-web-2025", content: JSON.stringify({ title: "Security Logging Failures", severity: "low", overview: "Insufficient logging enables undetected breaches.", summary: "No alerts on attack patterns.", affected_endpoints: [{ method: "GET", path: "/", description: "No WAF or SIEM alerts" }], evidence: [{ title: "Missing audit logs", request: "Review server logs", response: "No auth events logged" }], impact_items: [{ title: "Undetected Breach", explanation: "Attackers operate undetected." }], remediation_items: [{ action: "Comprehensive logging", fix: "Log all auth events.", code_snippet: null }], steps_to_reproduce: "1. Perform brute force. 2. Check logs. 3. Verify alerts.", references: [{ title: "OWASP A09", url: "https://owasp.org/Top10/A09_2025/" }] }) },
  { name: "A10:2025-SSRF", subcategory: "owasp-web-2025", content: JSON.stringify({ title: "Server-Side Request Forgery", severity: "high", overview: "Server makes requests to unintended destinations.", summary: "User-supplied URL fetched without validation.", affected_endpoints: [{ method: "POST", path: "/api/fetch", description: "URL not validated" }], evidence: [{ title: "AWS metadata", request: "POST /api/fetch with 169.254.169.254", response: "200 with IAM credentials" }], impact_items: [{ title: "Cloud Credential Theft", explanation: "Metadata endpoints exposed." }], remediation_items: [{ action: "URL validation", fix: "Block private IPs, use allowlists.", code_snippet: null }], steps_to_reproduce: "1. Identify fetch endpoints. 2. Supply internal URLs.", references: [{ title: "OWASP A10", url: "https://owasp.org/Top10/A10_2025/" }] }) },
];

const api = [
  { name: "API1:2023-Broken Object Level Auth", subcategory: "owasp-api-2023", content: JSON.stringify({ title: "Broken Object Level Authorization", severity: "critical", overview: "API endpoints fail to enforce object-level authorization.", summary: "Most common and severe API vulnerability.", affected_endpoints: [{ method: "GET", path: "/api/v1/receipts/{id}", description: "Receipt ID manipulable" }], evidence: [{ title: "BOLA on receipts", request: "GET /api/v1/receipts/9999", response: "200 OK with victim receipt data" }], impact_items: [{ title: "Unauthorized Data Access", explanation: "Access any object by ID." }], remediation_items: [{ action: "Auth checks", fix: "Verify user owns the object.", code_snippet: null }], steps_to_reproduce: "1. Authenticate as User A. 2. Access User B object. 3. Observe data.", references: [{ title: "OWASP API1", url: "https://owasp.org/API-Security/editions/2023/en/0xa1/" }] }) },
  { name: "API2:2023-Broken Authentication", subcategory: "owasp-api-2023", content: JSON.stringify({ title: "Broken Authentication", severity: "critical", overview: "Authentication mechanisms implemented incorrectly.", summary: "Weak passwords, token leakage, weak JWT signing.", affected_endpoints: [{ method: "POST", path: "/api/v1/auth/login", description: "No rate limiting" }], evidence: [{ title: "Weak JWT", request: "GET /profile with alg=none token", response: "200 OK" }], impact_items: [{ title: "Account Takeover", explanation: "Compromise passwords/tokens." }], remediation_items: [{ action: "Strong tokens", fix: "Use RS256/ES256 JWT.", code_snippet: null }], steps_to_reproduce: "1. Analyze JWT. 2. Change alg to none. 3. Verify acceptance.", references: [{ title: "OWASP API2", url: "https://owasp.org/API-Security/editions/2023/en/0xa2/" }] }) },
  { name: "API3:2023-Broken Object Property Auth", subcategory: "owasp-api-2023", content: JSON.stringify({ title: "Broken Object Property Authorization", severity: "high", overview: "APIs expose more object properties than allowed.", summary: "Extra fields returned or mass assignment possible.", affected_endpoints: [{ method: "GET", path: "/api/v1/users/me", description: "Returns sensitive fields" }], evidence: [{ title: "Exposed admin flag", request: "GET /users/me", response: "200 OK with isAdmin and passwordHash" }], impact_items: [{ title: "Privilege Escalation", explanation: "Modify hidden fields." }], remediation_items: [{ action: "Use DTOs", fix: "Control exposed and accepted fields.", code_snippet: null }], steps_to_reproduce: "1. GET /users/me. 2. Observe sensitive fields. 3. PUT isAdmin=true.", references: [{ title: "OWASP API3", url: "https://owasp.org/API-Security/editions/2023/en/0xa3/" }] }) },
  { name: "API4:2023-Unrestricted Resource Consumption", subcategory: "owasp-api-2023", content: JSON.stringify({ title: "Unrestricted Resource Consumption", severity: "high", overview: "APIs lack protections against excessive resource use.", summary: "No rate limiting, quotas, or resource controls.", affected_endpoints: [{ method: "POST", path: "/api/v1/reports/generate", description: "Expensive report generation" }], evidence: [{ title: "No rate limit", request: "POST /reports/generate", response: "202 Accepted immediately" }], impact_items: [{ title: "DoS", explanation: "Exhaust resources and crash." }], remediation_items: [{ action: "Rate limiting", fix: "Limit per user/IP.", code_snippet: null }], steps_to_reproduce: "1. Send rapid requests. 2. Observe no throttling.", references: [{ title: "OWASP API4", url: "https://owasp.org/API-Security/editions/2023/en/0xa4/" }] }) },
  { name: "API5:2023-Broken Function Level Auth", subcategory: "owasp-api-2023", content: JSON.stringify({ title: "Broken Function Level Authorization", severity: "high", overview: "APIs lack function-level permission checks.", summary: "Misconfigured ACLs or missing role validation.", affected_endpoints: [{ method: "DELETE", path: "/api/v1/admin/users", description: "Accessible to normal users" }], evidence: [{ title: "Admin endpoint accessible", request: "DELETE /admin/users/123", response: "200 OK" }], impact_items: [{ title: "Privilege Escalation", explanation: "Normal users perform admin actions." }], remediation_items: [{ action: "Deny by default", fix: "Check roles before sensitive functions.", code_snippet: null }], steps_to_reproduce: "1. Authenticate as standard user. 2. Send admin requests. 3. Observe success.", references: [{ title: "OWASP API5", url: "https://owasp.org/API-Security/editions/2023/en/0xa5/" }] }) },
  { name: "API6:2023-Unrestricted Business Flows", subcategory: "owasp-api-2023", content: JSON.stringify({ title: "Unrestricted Access to Sensitive Business Flows", severity: "medium", overview: "APIs expose business flows without compensating controls.", summary: "Automated abuse of purchasing, ticketing.", affected_endpoints: [{ method: "POST", path: "/api/v1/orders", description: "Bulk order creation" }], evidence: [{ title: "Unlimited orders", request: "POST /orders", response: "201 Created repeatedly" }], impact_items: [{ title: "Business Loss", explanation: "Inventory manipulation." }], remediation_items: [{ action: "Device fingerprinting", fix: "CAPTCHA, rate limiting.", code_snippet: null }], steps_to_reproduce: "1. Identify sensitive flows. 2. Automate requests.", references: [{ title: "OWASP API6", url: "https://owasp.org/API-Security/editions/2023/en/0xa6/" }] }) },
  { name: "API7:2023-SSRF", subcategory: "owasp-api-2023", content: JSON.stringify({ title: "Server-Side Request Forgery (SSRF)", severity: "high", overview: "APIs fetch remote resources without URL validation.", summary: "Attacker coerces server to make requests to internal services.", affected_endpoints: [{ method: "POST", path: "/api/v1/webhook/register", description: "URL not validated" }], evidence: [{ title: "AWS metadata access", request: "POST /webhook with 169.254.169.254", response: "200 with IAM credentials" }], impact_items: [{ title: "Internal Network Access", explanation: "Access internal services." }], remediation_items: [{ action: "Deny by default", fix: "Block private IPs, use allowlists.", code_snippet: null }], steps_to_reproduce: "1. Identify fetch endpoints. 2. Supply internal URLs.", references: [{ title: "OWASP API7", url: "https://owasp.org/API-Security/editions/2023/en/0xa7/" }] }) },
  { name: "API8:2023-Security Misconfiguration", subcategory: "owasp-api-2023", content: JSON.stringify({ title: "Security Misconfiguration", severity: "medium", overview: "APIs deployed with insecure defaults.", summary: "Verbose errors, unnecessary methods, default accounts.", affected_endpoints: [{ method: "OPTIONS", path: "/", description: "Verbose server info" }], evidence: [{ title: "Stack trace leakage", request: "GET /users/search?sort=invalid", response: "500 with stack trace" }], impact_items: [{ title: "Information Disclosure", explanation: "Reveal internal details." }], remediation_items: [{ action: "Harden config", fix: "Disable unnecessary features.", code_snippet: null }], steps_to_reproduce: "1. Send malformed requests. 2. Observe verbose errors.", references: [{ title: "OWASP API8", url: "https://owasp.org/API-Security/editions/2023/en/0xa8/" }] }) },
  { name: "API9:2023-Improper Inventory", subcategory: "owasp-api-2023", content: JSON.stringify({ title: "Improper Inventory Management", severity: "medium", overview: "APIs expose outdated or undocumented endpoints.", summary: "Old versions, test endpoints less secure.", affected_endpoints: [{ method: "GET", path: "/api/v1/test/users", description: "Test endpoint still active" }], evidence: [{ title: "Old API version", request: "GET /api/v0/users/1", response: "200 with plaintext password" }], impact_items: [{ title: "Data Breach", explanation: "Old endpoints weaker security." }], remediation_items: [{ action: "Maintain inventory", fix: "Document and retire old versions.", code_snippet: null }], steps_to_reproduce: "1. Discover hidden endpoints. 2. Test deprecated versions.", references: [{ title: "OWASP API9", url: "https://owasp.org/API-Security/editions/2023/en/0xa9/" }] }) },
  { name: "API10:2023-Unsafe API Consumption", subcategory: "owasp-api-2023", content: JSON.stringify({ title: "Unsafe Consumption of APIs", severity: "high", overview: "APIs consume third-party data without validation.", summary: "Injection via compromised external APIs.", affected_endpoints: [{ method: "POST", path: "/api/v1/integrations/fetch", description: "External data consumed" }], evidence: [{ title: "Unsanitized external data", request: "GET /profile/picture", response: "URL contains javascript:alert(1)" }], impact_items: [{ title: "Injection Attacks", explanation: "XSS, SQLi from third parties." }], remediation_items: [{ action: "Validate external data", fix: "Treat third-party data as untrusted.", code_snippet: null }], steps_to_reproduce: "1. Identify third-party integrations. 2. Inject payloads.", references: [{ title: "OWASP API10", url: "https://owasp.org/API-Security/editions/2023/en/0xaa/" }] }) },
];

const llm = [
  { name: "LLM01:2025-Prompt Injection", subcategory: "owasp-llm-2025", content: JSON.stringify({ title: "Prompt Injection", severity: "critical", overview: "Attackers manipulate LLM inputs.", summary: "Direct and indirect prompt injection.", affected_endpoints: [{ method: "POST", path: "/api/v1/chat", description: "User passed directly to model" }], evidence: [{ title: "Instruction override", request: "POST /chat with ignore instructions", response: "System prompt leaked" }], impact_items: [{ title: "Data Exfiltration", explanation: "Extract system prompts." }], remediation_items: [{ action: "Input validation", fix: "Validate user input.", code_snippet: null }], steps_to_reproduce: "1. Send injection payloads. 2. Observe behavior change.", references: [{ title: "OWASP LLM01", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }] }) },
  { name: "LLM02:2025-Insecure Output", subcategory: "owasp-llm-2025", content: JSON.stringify({ title: "Insecure Output Handling", severity: "high", overview: "LLM output passed to downstream components.", summary: "Enables XSS, SSRF, SQL injection.", affected_endpoints: [{ method: "POST", path: "/api/v1/generate", description: "Rendered in browser" }], evidence: [{ title: "XSS via output", request: "POST /generate with JS payload", response: "script tag in response" }], impact_items: [{ title: "XSS", explanation: "Malicious output executes in browser." }], remediation_items: [{ action: "Treat as untrusted", fix: "Validate and sanitize all output.", code_snippet: null }], steps_to_reproduce: "1. Request malicious content. 2. Observe in UI.", references: [{ title: "OWASP LLM02", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }] }) },
  { name: "LLM03:2025-Training Data Poisoning", subcategory: "owasp-llm-2025", content: JSON.stringify({ title: "Training Data Poisoning", severity: "medium", overview: "Malicious data in training corpus.", summary: "Backdoors and misinformation.", affected_endpoints: [{ method: "POST", path: "/api/v1/finetune", description: "Fine-tuning endpoint" }], evidence: [{ title: "Poisoned embeddings", request: "GET /search?q=product", response: "Competitor promoted" }], impact_items: [{ title: "Misinformation", explanation: "Model outputs bias." }], remediation_items: [{ action: "Data validation", fix: "Validate training sources.", code_snippet: null }], steps_to_reproduce: "1. Check training sources. 2. Inject poisoned data.", references: [{ title: "OWASP LLM03", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }] }) },
  { name: "LLM04:2025-Model DoS", subcategory: "owasp-llm-2025", content: JSON.stringify({ title: "Model Denial of Service", severity: "high", overview: "Resource-heavy operations.", summary: "Excessive context window or recursive tool invocations.", affected_endpoints: [{ method: "POST", path: "/api/v1/chat", description: "Resource exhaustion" }], evidence: [{ title: "Context exhaustion", request: "POST /chat with huge input", response: "Processing takes minutes" }], impact_items: [{ title: "Service Degradation", explanation: "High resource usage impacts others." }], remediation_items: [{ action: "Input limits", fix: "Limit input size and recursion.", code_snippet: null }], steps_to_reproduce: "1. Send large inputs. 2. Trigger recursive calls.", references: [{ title: "OWASP LLM04", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }] }) },
  { name: "LLM05:2025-Supply Chain", subcategory: "owasp-llm-2025", content: JSON.stringify({ title: "Supply Chain Vulnerabilities", severity: "high", overview: "Vulnerable dependencies in LLM lifecycle.", summary: "Unvetted models, poisoned data, vulnerable pipelines.", affected_endpoints: [{ method: "GET", path: "/api/v1/models/list", description: "Lists installed models" }], evidence: [{ title: "Vulnerable dependency", request: "GET /models/list", response: "custom-model-v1.0" }], impact_items: [{ title: "Backdoors", explanation: "Compromised models." }], remediation_items: [{ action: "Supply chain validation", fix: "Verify provenance, use signed models.", code_snippet: null }], steps_to_reproduce: "1. Review model sources. 2. Check signatures.", references: [{ title: "OWASP LLM05", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }] }) },
  { name: "LLM06:2025-Sensitive Info Disclosure", subcategory: "owasp-llm-2025", content: JSON.stringify({ title: "Sensitive Information Disclosure", severity: "critical", overview: "LLMs reveal sensitive information.", summary: "Memorized and regurgitated PII, passwords.", affected_endpoints: [{ method: "POST", path: "/api/v1/completion", description: "Data extraction" }], evidence: [{ title: "PII extraction", request: "POST /completion with partial credential", response: "Password123!" }], impact_items: [{ title: "Data Breach", explanation: "Leakage of training data." }], remediation_items: [{ action: "Data sanitization", fix: "Remove PII from training data.", code_snippet: null }], steps_to_reproduce: "1. Craft extraction prompts. 2. Search for PII.", references: [{ title: "OWASP LLM06", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }] }) },
  { name: "LLM07:2025-Insecure Plugin Design", subcategory: "owasp-llm-2025", content: JSON.stringify({ title: "Insecure Plugin Design", severity: "high", overview: "Plugins execute with excessive permissions.", summary: "Plugins trust LLM output without validation.", affected_endpoints: [{ method: "POST", path: "/api/v1/plugins/execute", description: "Plugin exec" }], evidence: [{ title: "Unauthorized action", request: "POST /plugins/execute email send", response: "Email sent without auth" }], impact_items: [{ title: "Unauthorized Actions", explanation: "Plugins act on behalf of users." }], remediation_items: [{ action: "Least privilege", fix: "Validate inputs, limit permissions.", code_snippet: null }], steps_to_reproduce: "1. Enumerate plugins. 2. Test permissions.", references: [{ title: "OWASP LLM07", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }] }) },
  { name: "LLM08:2025-Excessive Agency", subcategory: "owasp-llm-2025", content: JSON.stringify({ title: "Excessive Agency", severity: "high", overview: "LLM agents have excessive autonomy.", summary: "Destructive actions from adversarial inputs.", affected_endpoints: [{ method: "POST", path: "/api/v1/agent/execute", description: "Agent execution" }], evidence: [{ title: "File deletion", request: "POST /agent/execute", response: "Deleted files without confirmation" }], impact_items: [{ title: "Data Destruction", explanation: "Agents delete data." }], remediation_items: [{ action: "Restrict capabilities", fix: "Require approval for destructive actions.", code_snippet: null }], steps_to_reproduce: "1. Identify agent capabilities. 2. Request destruction.", references: [{ title: "OWASP LLM08", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }] }) },
  { name: "LLM09:2025-Overreliance", subcategory: "owasp-llm-2025", content: JSON.stringify({ title: "Overreliance", severity: "medium", overview: "Systems overly trust LLM outputs.", summary: "Misinformation, bad code, security vulnerabilities.", affected_endpoints: [{ method: "POST", path: "/api/v1/generate/code", description: "Code generation" }], evidence: [{ title: "Insecure code", request: "POST /generate/code login", response: "Hardcoded credentials" }], impact_items: [{ title: "Security Vulns", explanation: "Generated code contains backdoors." }], remediation_items: [{ action: "Human review", fix: "Review all generated code.", code_snippet: null }], steps_to_reproduce: "1. Request code generation. 2. Review for issues.", references: [{ title: "OWASP LLM09", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }] }) },
  { name: "LLM10:2025-Model Theft", subcategory: "owasp-llm-2025", content: JSON.stringify({ title: "Model Theft", severity: "medium", overview: "Unauthorized access to models.", summary: "Extraction, side channels, unauthorized access.", affected_endpoints: [{ method: "POST", path: "/api/v1/chat", description: "Model query" }], evidence: [{ title: "Excessive queries", request: "POST /chat with extraction prompt", response: "Detailed behavior replication data" }], impact_items: [{ title: "IP Theft", explanation: "Functionality replicated." }], remediation_items: [{ action: "Query limits", fix: "Rate limit and watermark outputs.", code_snippet: null }], steps_to_reproduce: "1. Query with extraction-style prompts. 2. Monitor volume.", references: [{ title: "OWASP LLM10", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }] }) },
];

const other = [
  { name: "Scope Questionnaire", category: "requirements", subcategory: "scope", content: "# Scope Questionnaire\\n\\n1. In-scope systems:\\n2. Out-of-scope systems:\\n3. Testing windows:\\n4. Emergency contacts:\\n5. Acceptable hours:\\n\\n## Objectives\\n- Primary security concerns?\\n- Compliance frameworks?\\n- Previous findings to verify?\\n\\n## Access Requirements\\n- VPN or jump host?\\n- Test account credentials?\\n- API keys?" },
  { name: "Testing Objectives", category: "requirements", subcategory: "objectives", content: "# Testing Objectives\\n\\n## Goals\\n1. Identify vulnerabilities.\\n2. Assess business impact.\\n3. Validate security controls.\\n4. Provide remediation guidance.\\n\\n## Methodology\\n- OWASP Testing Guide v4.2\\n- PTES Technical Guidelines\\n- NIST SP 800-115\\n\\n## Deliverables\\n- Executive summary\\n- Detailed findings report\\n- Remediation roadmap" },
  { name: "Pre-Engagement Checklist", category: "checklist", subcategory: "pre-engagement", content: "# Pre-Engagement Checklist\\n\\n- [ ] SOW signed\\n- [ ] RoE agreed\\n- [ ] Testing window scheduled\\n- [ ] VPN/access received\\n- [ ] Target IP ranges confirmed\\n- [ ] Emergency contacts verified\\n- [ ] Backup procedures confirmed\\n- [ ] Legal authorization obtained\\n- [ ] Team assignments completed\\n- [ ] Tools and environment prepared" },
  { name: "Post-Engagement Checklist", category: "checklist", subcategory: "post-engagement", content: "# Post-Engagement Checklist\\n\\n- [ ] All findings documented\\n- [ ] CVSS scores calculated\\n- [ ] Risk ratings validated\\n- [ ] Executive summary written\\n- [ ] Report peer reviewed\\n- [ ] Client debrief scheduled\\n- [ ] Report delivered securely\\n- [ ] Retest scope agreed\\n- [ ] Knowledge base updated\\n- [ ] Lessons learned captured" },
  { name: "Methodology Checklist", category: "checklist", subcategory: "methodology", content: "# Methodology Checklist\\n\\n## Info Gathering\\n- [ ] OSINT\\n- [ ] DNS/subdomain enumeration\\n- [ ] Technology fingerprinting\\n\\n## Vulnerability Discovery\\n- [ ] Automated scanning\\n- [ ] Manual testing\\n- [ ] Business logic testing\\n- [ ] Auth and session testing\\n- [ ] Input validation testing\\n- [ ] Authorization testing\\n\\n## Exploitation\\n- [ ] PoC for each finding\\n- [ ] Impact assessment\\n- [ ] Post-exploitation analysis" },
  { name: "SOW Cover Letter", category: "email", subcategory: "sow", content: "Dear {{client_name}},\\n\\nThank you for engaging {{company_name}}. Attached is the Statement of Work for {{engagement_name}} scheduled for {{date}}.\\n\\nPlease review, sign, and return.\\n\\nBest regards,\\n{{sender_name}}" },
  { name: "Requirements Request", category: "email", subcategory: "requirements", content: "Dear {{client_name}},\\n\\nTo ensure a smooth engagement, we need:\\n1. In-scope IP ranges / domains\\n2. VPN credentials\\n3. Test account credentials\\n4. API documentation and keys\\n5. Emergency contacts\\n6. Maintenance windows\\n\\nPlease provide at least 3 business days before start date.\\n\\nBest,\\n{{sender_name}}" },
  { name: "Status Update", category: "email", subcategory: "status", content: "Dear {{client_name}},\\n\\nStatus update for {{engagement_name}} as of {{date}}.\\n\\n## Progress\\n- Testing: X% complete\\n- Findings so far: Y\\n\\n## Next Steps\\n- Continue testing\\n- Prepare preliminary findings\\n\\n## Blockers\\n- None\\n\\nBest,\\n{{sender_name}}" },
  { name: "Report Delivery", category: "email", subcategory: "delivery", content: "Dear {{client_name}},\\n\\nThe assessment for {{engagement_name}} is complete.\\n\\nYour report is available via the secure portal.\\n\\n## Next Steps\\n1. Review findings\\n2. Schedule debrief call\\n3. Confirm retest scope\\n\\nBest regards,\\n{{sender_name}}" },
  { name: "Daily Status Report", category: "status_report", subcategory: "daily", content: "# Daily Status Report\\n\\n**Date:** {{date}}\\n**Engagement:** {{engagement_name}}\\n**Consultant:** {{sender_name}}\\n\\n## Activity Summary\\n- Hours worked: X\\n- Systems tested: Y\\n\\n## Findings\\n| Title | Severity | Status |\\n|-------|----------|--------|\\n\\n## Blockers / Risks\\n\\n## Plan for Tomorrow" },
  { name: "Weekly Status Report", category: "status_report", subcategory: "weekly", content: "# Weekly Status Report\\n\\n**Week:** {{date}}\\n**Engagement:** {{engagement_name}}\\n\\n## Progress\\n- Overall completion: X%\\n- Testing hours: Y\\n- Findings to date: Z\\n\\n## Risk Dashboard\\n| Severity | Count | Trend |\\n|----------|-------|-------|\\n\\n## Key Milestones\\n\\n## Upcoming Activities\\n\\n## Issues / Escalations" },
  { name: "Monthly Status Report", category: "status_report", subcategory: "monthly", content: "# Monthly Status Report\\n\\n**Month:** {{date}}\\n**Engagement:** {{engagement_name}}\\n\\n## Executive Summary\\n[High-level summary]\\n\\n## Metrics\\n- Total engagements: X\\n- Findings discovered: Y\\n- Findings remediated: Z\\n\\n## High-Risk Findings\\n\\n## Retest Results\\n\\n## Recommendations\\n\\n## Next Month Plan" },
  { name: "Engagement Progress Summary", category: "engagement_status", subcategory: "summary", content: "# Engagement Progress Summary\\n\\n**Engagement:** {{engagement_name}}\\n**Client:** {{company_name}}\\n**Date:** {{date}}\\n\\n## Status\\n- Phase: [Planning / Execution / Reporting / Retest]\\n- Overall progress: X%\\n\\n## Findings Summary\\n| Severity | Open | Closed | Total |\\n|----------|------|--------|-------|\\n\\n## Scope Coverage\\n\\n## Budget / Hours\\n\\n## Action Items" },
];

writeJson('owasp_web.json', web);
writeJson('owasp_api.json', api);
writeJson('owasp_llm.json', llm);
writeJson('other.json', other);
console.log('Done');
