#!/bin/sh
# checks.sh — Pre-commit gate for SecuritySmith
#
# Runs formatting, linting, and tests. Fast — no release build.
# Stops on first failure. Exit 0 = all pass, exit 1 = something failed.
#
# Usage:
#   ./scripts/checks.sh                 Run all checks
#   ./scripts/checks.sh --install-hook  Install git pre-commit hook
#
set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PROJECT_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

pass() { printf "  ${GREEN}✓${NC} %s\n" "$1"; }
fail() { printf "  ${RED}✗${NC} %s\n" "$1"; }

ERRORS=0

run_check() {
    local label="$1"
    shift
    printf "  → %s\n" "$label"
    if (cd "$PROJECT_DIR" && "$@") > /tmp/sm-checks.log 2>&1; then
        pass "$label"
    else
        fail "$label"
        cat /tmp/sm-checks.log | tail -20
        ERRORS=$((ERRORS + 1))
        return 1
    fi
}

# ─── Install pre-commit hook ────────────────────────────
if [ "${1:-}" = "--install-hook" ]; then
    HOOK="$PROJECT_DIR/.git/hooks/pre-commit"
    printf "Installing pre-commit hook at %s\n" "$HOOK"
    cat > "$HOOK" << 'HOOK_EOF'
#!/bin/sh
# Auto-generated by ./scripts/checks.sh
exec ./scripts/checks.sh
HOOK_EOF
    chmod +x "$HOOK"
    printf "Done. Commits will now run checks automatically.\n"
    printf "To bypass: git commit --no-verify\n"
    exit 0
fi

# ─── Checks ──────────────────────────────────────────────
echo "═══════════════════════════════════════════════════"
echo "  SecuritySmith Pre-Commit Checks"
echo "═══════════════════════════════════════════════════"
echo ""

# 1. Formatting
run_check "cargo fmt -- --check" cargo fmt -- --check || { echo ""; echo "Fix: cargo fmt"; exit 1; }

# 2. Linting (zero warnings allowed)
run_check "cargo clippy --all-targets -- -D warnings" cargo clippy --all-targets -- -D warnings || { echo ""; echo "Fix: cargo clippy --fix"; exit 1; }

# 3. Tests
run_check "cargo test" cargo test || { echo ""; echo "Fix failing tests"; exit 1; }

# ─── Summary ────────────────────────────────────────────
echo ""
if [ $ERRORS -eq 0 ]; then
    echo "  ${GREEN}ALL CHECKS PASSED${NC} — safe to commit."
    exit 0
else
    echo "  ${RED}$ERRORS CHECK(S) FAILED${NC} — fix before committing."
    exit 1
fi