pub mod commands;
pub mod crypto;
pub mod db;
pub mod parsers;
pub mod report_engine;
pub mod state;

use commands::{
    activity_log, ai, analytics, attachments, auth, calendar, checklists, clients, compliance,
    contacts, credentials, documents, email, engagements, findings, findings_import, invoices,
    news, notifications, portability, reports, retests, scope, search, settings, templates,
    time_entries,
};
use state::AppState;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .manage(AppState::default())
        .invoke_handler(tauri::generate_handler![
            auth::is_vault_initialized,
            auth::create_vault,
            auth::unlock_vault,
            auth::validate_recovery_words,
            auth::recover_vault,
            auth::rotate_recovery_phrase,
            auth::change_master_password,
            settings::get_setting,
            settings::set_setting,
            settings::list_settings,
            settings::get_boot_theme,
            settings::test_ollama_connection,
            clients::create_client,
            clients::get_client,
            clients::update_client,
            clients::delete_client,
            clients::list_clients,
            clients::get_dashboard_stats,
            engagements::create_engagement,
            engagements::get_engagement,
            engagements::update_engagement,
            engagements::archive_engagement,
            engagements::list_engagements,
            engagements::transition_engagement_status,
            engagements::toggle_engagement_gate,
            credentials::create_credential,
            credentials::get_credential,
            credentials::update_credential,
            credentials::delete_credential,
            credentials::list_credentials,
            findings::create_finding,
            findings::get_finding,
            findings::update_finding,
            findings::update_finding_status,
            findings::duplicate_finding,
            findings::archive_finding,
            findings::list_findings,
            findings::get_finding_counts,
            templates::list_templates,
            templates::get_template,
            templates::create_template,
            templates::update_template,
            templates::duplicate_template,
            templates::delete_template,
            templates::save_finding_as_template,
            activity_log::list_activity_log,
            activity_log::export_activity_log,
            activity_log::get_entity_history,
            activity_log::prune_audit_log,
            calendar::list_calendar_events,
            calendar::get_active_reminders,
            calendar::dismiss_reminder,
            findings_import::parse_import_file,
            findings_import::commit_import,
            reports::list_reports,
            reports::get_report,
            reports::create_report,
            reports::update_report,
            reports::archive_report,
            reports::generate_report_pdf,
            documents::list_documents,
            documents::get_document,
            documents::create_document,
            documents::update_document,
            documents::archive_document,
            documents::render_document_placeholders,
            invoices::list_invoices,
            invoices::get_invoice,
            invoices::create_invoice,
            invoices::update_invoice_status,
            invoices::archive_invoice,
            invoices::add_invoice_item,
            invoices::update_invoice_item,
            invoices::delete_invoice_item,
            invoices::generate_invoice_pdf,
            news::list_feeds,
            news::create_feed,
            news::delete_feed,
            news::update_feed,
            news::mark_article_read,
            news::get_client_alerts,
            news::list_news_articles,
            news::seed_default_news_feeds,
            news::refresh_feeds,
            ai::ai_chat,
            ai::ai_approve_tool_call,
            ai::ai_reject_tool_call,
            ai::ai_cancel,
            email::send_test_email,
            email::test_smtp_connection,
            email::send_email,
            email::get_follow_up_reminders,
            portability::export_vault_json,
            portability::get_export_tree,
            portability::create_export,
            portability::create_encrypted_export,
            portability::is_import_encrypted,
            portability::decrypt_import_to_temp,
            portability::preview_import,
            portability::execute_import,
            // PROP-020 Evidence Attachments
            attachments::upload_attachment,
            attachments::list_attachments,
            attachments::delete_attachment,
            attachments::rename_attachment,
            attachments::reorder_attachments,
            attachments::read_attachment_file,
            attachments::get_attachment_thumbnail,
            attachments::get_total_attachment_storage,
            // PROP-021 Client Contacts
            contacts::list_contacts,
            contacts::get_contact,
            contacts::create_contact,
            contacts::update_contact,
            contacts::delete_contact,
            // PROP-022 Retest Remediation
            retests::create_retest_engagement,
            retests::list_retest_engagements,
            retests::get_retest_comparison,
            retests::bulk_update_finding_status,
            retests::get_overdue_findings,
            // PROP-023 Scope Assets
            scope::list_scope_items,
            scope::create_scope_item,
            scope::update_scope_item,
            scope::delete_scope_item,
            scope::bulk_import_scope_items,
            scope::export_scope_text,
            // PROP-024 Time Tracking
            time_entries::list_time_entries,
            time_entries::create_time_entry,
            time_entries::update_time_entry,
            time_entries::delete_time_entry,
            time_entries::get_weekly_summary,
            time_entries::get_budget_status,
            time_entries::create_invoice_from_time,
            // PROP-025 Analytics
            analytics::get_severity_distribution,
            analytics::get_top_categories,
            analytics::get_findings_over_time,
            analytics::get_remediation_rate,
            analytics::get_revenue_by_client,
            analytics::get_engagement_timeline,
            analytics::get_time_by_activity,
            analytics::get_budget_vs_actual,
            // PROP-027 Methodology Checklists
            checklists::list_checklists,
            checklists::get_checklist_items,
            checklists::create_checklist,
            checklists::create_checklist_item,
            checklists::assign_checklist_to_engagement,
            checklists::get_engagement_checklist,
            checklists::update_engagement_checklist_item,
            checklists::get_checklist_coverage,
            // PROP-028 Global Search
            search::global_search,
            search::rebuild_search_index_command,
            // PROP-029 Notification Center
            notifications::get_notifications,
            notifications::dismiss_notification,
            notifications::get_notification_count,
            // PROP-030 Compliance Mapping
            compliance::list_frameworks,
            compliance::list_controls,
            compliance::create_framework,
            compliance::create_control,
            compliance::map_finding_to_control,
            compliance::get_finding_mappings,
            compliance::get_engagement_compliance_coverage,
            compliance::remove_compliance_mapping,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
